### ISSUE TITLE
Compiling your source

### ISSUE THREAD

**Issue by shulace13** [slowsingle/openpose_ros#1]
Hi there
I am currently trying to compile your package into my work space.

I changed the dependencies and the directories to the libraries for openpose but I get this error

/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp: In constructor ‘OpenposeDetecter::OpenposeDetecter()’:
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:77:94: error: too many initializers for ‘op::CvMatToOpInput’
     op::CvMatToOpInput cvMatToOpInput_{netInputSize, FLAGS_num_scales, (float)FLAGS_scale_gap};
                                                                                              ^
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:79:52: error: too many initializers for ‘op::CvMatToOpOutput’
     op::CvMatToOpOutput cvMatToOpOutput_{outputSize};
                                                    ^
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:83:86: error: no matching function for call to ‘op::PoseExtractorCaffe::PoseExtractorCaffe(<brace-enclosed initializer list>)’
                                               FLAGS_model_folder, FLAGS_num_gpu_start};
                                                                                      ^
In file included from /home/amsl/openpose/include/openpose/pose/headers.hpp:10:0,
                 from /home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:16:
/home/amsl/openpose/include/openpose/pose/poseExtractorCaffe.hpp:13:9: note: candidate: op::PoseExtractorCaffe::PoseExtractorCaffe(op::PoseModel, const string&, int, const std::vector<op::HeatMapType>&, op::ScaleMode, bool)
         PoseExtractorCaffe(const PoseModel poseModel, const std::string& modelFolder, const int gpuId,
         ^
/home/amsl/openpose/include/openpose/pose/poseExtractorCaffe.hpp:13:9: note:   candidate expects 6 arguments, 7 provided
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:86:131: error: no matching function for call to ‘op::PoseRenderer::PoseRenderer(<brace-enclosed initializer list>)’
     op::PoseRenderer poseRenderer_{netOutputSize, outputSize, poseModel, nullptr, !FLAGS_disable_blending, (float)FLAGS_alpha_pose};
                                                                                                                                   ^
In file included from /home/amsl/openpose/include/openpose/pose/poseCpuRenderer.hpp:9:0,
                 from /home/amsl/openpose/include/openpose/pose/headers.hpp:8,
                 from /home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:16:
/home/amsl/openpose/include/openpose/pose/poseRenderer.hpp:12:9: note: candidate: op::PoseRenderer::PoseRenderer(op::PoseModel)
         PoseRenderer(const PoseModel poseModel);
         ^
/home/amsl/openpose/include/openpose/pose/poseRenderer.hpp:12:9: note:   candidate expects 1 argument, 6 provided
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:86:22: error: cannot declare variable ‘poseRenderer_’ to be of abstract type ‘op::PoseRenderer’
     op::PoseRenderer poseRenderer_{netOutputSize, outputSize, poseModel, nullptr, !FLAGS_disable_blending, (float)FLAGS_alpha_pose};
                      ^
In file included from /home/amsl/openpose/include/openpose/pose/poseCpuRenderer.hpp:9:0,
                 from /home/amsl/openpose/include/openpose/pose/headers.hpp:8,
                 from /home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:16:
/home/amsl/openpose/include/openpose/pose/poseRenderer.hpp:9:18: note:   because the following virtual functions are pure within ‘op::PoseRenderer’:
     class OP_API PoseRenderer
                  ^
/home/amsl/openpose/include/openpose/pose/poseRenderer.hpp:16:45: note: 	virtual std::pair<int, std::__cxx11::basic_string<char> > op::PoseRenderer::renderPose(op::Array<float>&, const op::Array<float>&, float, float)
         virtual std::pair<int, std::string> renderPose(Array<float>& outputData, const Array<float>& poseKeypoints,
                                             ^
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:89:52: error: too many initializers for ‘op::OpOutputToCvMat’
     op::OpOutputToCvMat opOutputToCvMat_{outputSize};
                                                    ^
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp: In member function ‘void OpenposeDetecter::imageCallback(const ImageConstPtr&)’:
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:131:62: error: ‘class op::CvMatToOpInput’ has no member named ‘format’
     std::tie(netInputArray, scaleRatios) = (*cvMatToOpInput).format(cv_ptr->image);
                                                              ^
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:134:68: error: ‘class op::CvMatToOpOutput’ has no member named ‘format’
     std::tie(scaleInputToOutput, outputArray) = (*cvMatToOpOutput).format(cv_ptr->image);
                                                                    ^
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:137:107: error: no matching function for call to ‘op::PoseExtractorCaffe::forwardPass(op::Array<float>&, <brace-enclosed initializer list>, std::vector<float>&)’
     (*poseExtractorCaffe).forwardPass(netInputArray, {cv_ptr->image.cols, cv_ptr->image.rows}, scaleRatios);
                                                                                                           ^
In file included from /home/amsl/openpose/include/openpose/pose/headers.hpp:10:0,
                 from /home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:16:
/home/amsl/openpose/include/openpose/pose/poseExtractorCaffe.hpp:22:14: note: candidate: virtual void op::PoseExtractorCaffe::forwardPass(const std::vector<op::Array<float> >&, const op::Point<int>&, const std::vector<double>&)
         void forwardPass(const std::vector<Array<float>>& inputNetData, const Point<int>& inputDataSize,
              ^
/home/amsl/openpose/include/openpose/pose/poseExtractorCaffe.hpp:22:14: note:   no known conversion for argument 1 from ‘op::Array<float>’ to ‘const std::vector<op::Array<float> >&’
/home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:238:62: error: no matching function for call to ‘op::PoseRenderer::renderPose(op::Array<float>&, const op::Array<float>&)’
         (*poseRenderer).renderPose(outputArray, poseKeypoints);
                                                              ^
In file included from /home/amsl/openpose/include/openpose/pose/poseCpuRenderer.hpp:9:0,
                 from /home/amsl/openpose/include/openpose/pose/headers.hpp:8,
                 from /home/amsl/ros_catkin_ws/src/openpose_ros/src/openpose_ros_node.cpp:16:
/home/amsl/openpose/include/openpose/pose/poseRenderer.hpp:16:45: note: candidate: virtual std::pair<int, std::__cxx11::basic_string<char> > op::PoseRenderer::renderPose(op::Array<float>&, const op::Array<float>&, float, float)
         virtual std::pair<int, std::string> renderPose(Array<float>& outputData, const Array<float>& poseKeypoints,
                                             ^
/home/amsl/openpose/include/openpose/pose/poseRenderer.hpp:16:45: note:   candidate expects 4 arguments, 2 provided
openpose_ros/CMakeFiles/openpose_ros_node.dir/build.make:62: recipe for target 'openpose_ros/CMakeFiles/openpose_ros_node.dir/src/openpose_ros_node.cpp.o' failed
make[2]: *** [openpose_ros/CMakeFiles/openpose_ros_node.dir/src/openpose_ros_node.cpp.o] Error 1
CMakeFiles/Makefile2:5779: recipe for target 'openpose_ros/CMakeFiles/openpose_ros_node.dir/all' failed
make[1]: *** [openpose_ros/CMakeFiles/openpose_ros_node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

Is there anyway you can help me out on this? Thanks in advance.

**Comment by slowsingle** [comment]
@shulace13 

The cause of some errors depend on the difference of version of openpose.
Some APIs has been changed. 

(example)
[old version] op::OpOutputToCvMat opOutputToCvMat{outputSize};
[latest version] op::OpOutputToCvMat opOutputToCvMat;
 
You have two solutions.
(I) you reinstall old openpose library. Maybe tag v1.0.0 works well.
(II) you rewrite openpose_ros_node.cpp with reference to "openpose/examples/tutorial_pose/1_extract_from_image.cpp".

**Comment by shulace13** [comment]
@slowsingle 
I see... Thanks for the advice!
I'll try my best.

**Comment by shulace13** [comment]
I'm sorry for commenting even after closing this,
I was wondering how to tag the old openpose library...
Do I change some parts in the makefile or do I need to download it again.
